from __future__ import annotations

SEED_ENTITIES: list[dict[str, object]] = [
    {"canonical_name": "OpenAI", "aliases": ["openai", "open ai"]},
    {"canonical_name": "Anthropic", "aliases": ["anthropic", "anthropic ai"]},
    {"canonical_name": "Mistral AI", "aliases": ["mistral", "mistral ai"]},
    {"canonical_name": "Perplexity", "aliases": ["perplexity", "perplexity ai"]},
    {"canonical_name": "Cohere", "aliases": ["cohere", "cohere ai"]},
    {"canonical_name": "Scale AI", "aliases": ["scale ai", "scale"]},
    {"canonical_name": "Databricks", "aliases": ["databricks"]},
    {"canonical_name": "Together AI", "aliases": ["together", "together ai"]},
    {"canonical_name": "Hugging Face", "aliases": ["hugging face", "huggingface"]},
    {"canonical_name": "Runway", "aliases": ["runway"]},
    {"canonical_name": "Stability AI", "aliases": ["stability ai", "stability"]},
    {"canonical_name": "Midjourney", "aliases": ["midjourney"]},
    {"canonical_name": "Pika", "aliases": ["pika"]},
    {"canonical_name": "Synthesia", "aliases": ["synthesia"]},
    {"canonical_name": "Character AI", "aliases": ["character ai", "character"]},
    {"canonical_name": "Grok", "aliases": ["grok", "x ai"]},
    {"canonical_name": "xAI", "aliases": ["xai", "x ai"]},
    {"canonical_name": "AI21 Labs", "aliases": ["ai21", "ai21 labs"]},
    {"canonical_name": "Adept", "aliases": ["adept"]},
    {"canonical_name": "Recurrent AI", "aliases": ["recurrent ai"]},
    {"canonical_name": "Aporia", "aliases": ["aporia"]},
    {"canonical_name": "Anyscale", "aliases": ["anyscale"]},
    {"canonical_name": "Weights & Biases", "aliases": ["weights and biases", "wandb"]},
    {"canonical_name": "LangChain", "aliases": ["langchain"]},
    {"canonical_name": "LlamaIndex", "aliases": ["llamaindex", "llama index"]},
    {"canonical_name": "Modal", "aliases": ["modal"]},
    {"canonical_name": "Replicate", "aliases": ["replicate"]},
    {"canonical_name": "Pinecone", "aliases": ["pinecone"]},
    {"canonical_name": "Nomic", "aliases": ["nomic"]},
    {"canonical_name": "Vespa", "aliases": ["vespa"]},
    {"canonical_name": "Unstructured", "aliases": ["unstructured"]},
    {"canonical_name": "Figure AI", "aliases": ["figure ai", "figure"]},
    {"canonical_name": "Osmo", "aliases": ["osmo"]},
    {"canonical_name": "Sierra", "aliases": ["sierra"]},
    {"canonical_name": "Harvey", "aliases": ["harvey"]},
    {"canonical_name": "DataRobot", "aliases": ["datarobot"]},
    {"canonical_name": "Appier", "aliases": ["appier"]},
    {"canonical_name": "NVIDIA", "aliases": ["nvidia"]},
    {"canonical_name": "Lambda", "aliases": ["lambda"]},
    {"canonical_name": "Fireworks AI", "aliases": ["fireworks ai", "fireworks"]},
    {"canonical_name": "Cresta", "aliases": ["cresta"]},
    {"canonical_name": "Baseten", "aliases": ["baseten"]},
    {"canonical_name": "OctoAI", "aliases": ["octo ai", "octoai"]},
    {"canonical_name": "VAST AI", "aliases": ["vast ai", "vast"]},
    {"canonical_name": "Pytorch Lightning", "aliases": ["pytorch lightning", "lightning ai"]},
    {"canonical_name": "MosaicML", "aliases": ["mosaicml", "mosaic ml"]},
    {"canonical_name": "SambaNova", "aliases": ["sambanova", "samba nova"]},
    {"canonical_name": "Fauna", "aliases": ["fauna"]},
    {"canonical_name": "Abridge", "aliases": ["abridge"]},
    {"canonical_name": "Graft", "aliases": ["graft"]},
    {"canonical_name": "Airtable", "aliases": ["airtable"]},
    {"canonical_name": "Notion", "aliases": ["notion"]},
    {"canonical_name": "Cursor", "aliases": ["cursor"]},
    {"canonical_name": "Lovable", "aliases": ["lovable"]},
    {"canonical_name": "Replit", "aliases": ["replit"]},
    {"canonical_name": "Bolt", "aliases": ["bolt"]},
    {"canonical_name": "Vercel", "aliases": ["vercel"]},
    {"canonical_name": "OpenRouter", "aliases": ["openrouter"]},
    {"canonical_name": "Gumloop", "aliases": ["gumloop"]},
]

__all__ = ["SEED_ENTITIES"]
